version: '2.3'
services:
    nocom-http:
        restart: unless-stopped
        image: registry.gitlab.com/fr1kin/nocom-http:latest
        volumes:
            - "/opt/nocom-http/locations.db:/opt/nocom-http/locations.db"
            - "/opt/nocom-http/admins.txt:/opt/nocom-http/admins.txt"
            - "/opt/nocom-http/logs:/opt/nocom-http/logs"
        working_dir: /opt/nocom-http
        ports:
            - "7373:8080"
