/*
 * This file is generated by jOOQ.
 */
package com.matt.nocom.server.postgres.codegen.routines;


import com.matt.nocom.server.postgres.codegen.DefaultSchema;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.lambda.tuple.Range;

import space.nerdsin.nocom.server.jooq.Int8RangeJOOQBinding;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RangeUnionCardinality extends AbstractRoutine<Long> {

    private static final long serialVersionUID = 906529633;

    /**
     * The parameter <code>range_union_cardinality.RETURN_VALUE</code>.
     */
    public static final Parameter<Long> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>range_union_cardinality._1</code>.
     */
    public static final Parameter<Range<Long>> _1 = Internal.createParameter("_1", org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"int8range\""), false, true, new Int8RangeJOOQBinding());

    /**
     * Create a new routine call instance
     */
    public RangeUnionCardinality() {
        super("range_union_cardinality", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

        setReturnParameter(RETURN_VALUE);
        addInParameter(_1);
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    public void set__1(Range<Long> value) {
        setValue(_1, value);
    }

    /**
     * Set the <code>_1</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void set__1(Field<Range<Long>> field) {
        setField(_1, field);
    }
}
