/*
 * This file is generated by jOOQ.
 */
package com.matt.nocom.server.postgres.codegen.routines;


import com.matt.nocom.server.postgres.codegen.DefaultSchema;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;



/**
 * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
 */
@java.lang.Deprecated
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StMinimumboundingcircle extends AbstractRoutine<Object> {

    private static final long serialVersionUID = 1903821633;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public static final Parameter<Object> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), false, false);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public static final Parameter<Object> INPUTGEOM = Internal.createParameter("inputgeom", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), false, false);

    /**
     * The parameter <code>st_minimumboundingcircle.segs_per_quarter</code>.
     */
    public static final Parameter<Integer> SEGS_PER_QUARTER = Internal.createParameter("segs_per_quarter", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("48", org.jooq.impl.SQLDataType.INTEGER)), true, false);

    /**
     * Create a new routine call instance
     */
    public StMinimumboundingcircle() {
        super("st_minimumboundingcircle", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""));

        setReturnParameter(RETURN_VALUE);
        addInParameter(INPUTGEOM);
        addInParameter(SEGS_PER_QUARTER);
    }

    /**
     * Set the <code>inputgeom</code> parameter IN value to the routine
     */
    public void setInputgeom(Object value) {
        setValue(INPUTGEOM, value);
    }

    /**
     * Set the <code>inputgeom</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setInputgeom(Field<Object> field) {
        setField(INPUTGEOM, field);
    }

    /**
     * Set the <code>segs_per_quarter</code> parameter IN value to the routine
     */
    public void setSegsPerQuarter(Integer value) {
        setValue(SEGS_PER_QUARTER, value);
    }

    /**
     * Set the <code>segs_per_quarter</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setSegsPerQuarter(Field<Integer> field) {
        setField(SEGS_PER_QUARTER, field);
    }
}
