/*
 * This file is generated by jOOQ.
 */
package com.matt.nocom.server.postgres.codegen.routines;


import com.matt.nocom.server.postgres.codegen.DefaultSchema;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;

import javax.annotation.processing.Generated;



/**
 * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
 */
@java.lang.Deprecated
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StWrapx extends AbstractRoutine<Object> {

    private static final long serialVersionUID = -14540397;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public static final Parameter<Object> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), false, false);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public static final Parameter<Object> GEOM = Internal.createParameter("geom", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), false, false);

    /**
     * The parameter <code>st_wrapx.wrap</code>.
     */
    public static final Parameter<Double> WRAP = Internal.createParameter("wrap", org.jooq.impl.SQLDataType.DOUBLE, false, false);

    /**
     * The parameter <code>st_wrapx.move</code>.
     */
    public static final Parameter<Double> MOVE = Internal.createParameter("move", org.jooq.impl.SQLDataType.DOUBLE, false, false);

    /**
     * Create a new routine call instance
     */
    public StWrapx() {
        super("st_wrapx", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""));

        setReturnParameter(RETURN_VALUE);
        addInParameter(GEOM);
        addInParameter(WRAP);
        addInParameter(MOVE);
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    public void setGeom(Object value) {
        setValue(GEOM, value);
    }

    /**
     * Set the <code>geom</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setGeom(Field<Object> field) {
        setField(GEOM, field);
    }

    /**
     * Set the <code>wrap</code> parameter IN value to the routine
     */
    public void setWrap(Double value) {
        setValue(WRAP, value);
    }

    /**
     * Set the <code>wrap</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setWrap(Field<Double> field) {
        setField(WRAP, field);
    }

    /**
     * Set the <code>move</code> parameter IN value to the routine
     */
    public void setMove(Double value) {
        setValue(MOVE, value);
    }

    /**
     * Set the <code>move</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setMove(Field<Double> field) {
        setField(MOVE, field);
    }
}
