CREATE TABLE Auth_Users (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR_IGNORECASE NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    level INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    debug BOOLEAN NOT NULL DEFAULT FALSE,
    login_timestamp TIMESTAMP DEFAULT NULL
);

CREATE TABLE Auth_Token (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  token UUID NOT NULL,
  address BLOB(128) NOT NULL,
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  user_id INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES Auth_Users(id)
      ON DELETE CASCADE
      ON UPDATE NO ACTION
);

CREATE TABLE Event (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    type VARCHAR_IGNORECASE DEFAULT 'None',
    caused_by VARCHAR_IGNORECASE DEFAULT 'Unknown',
    message VARCHAR NOT NULL
);
