/*
 * This file is generated by jOOQ.
 */
package com.matt.nocom.server.postgres.codegen.tables;


import com.matt.nocom.server.postgres.codegen.DefaultSchema;
import com.matt.nocom.server.postgres.codegen.Indexes;
import com.matt.nocom.server.postgres.codegen.Keys;
import com.matt.nocom.server.postgres.codegen.tables.records.AssociationsRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Associations extends TableImpl<AssociationsRecord> {

    private static final long serialVersionUID = 1631196409;

    /**
     * The reference instance of <code>associations</code>
     */
    public static final Associations ASSOCIATIONS = new Associations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AssociationsRecord> getRecordType() {
        return AssociationsRecord.class;
    }

    /**
     * The column <code>associations.cluster_id</code>.
     */
    public final TableField<AssociationsRecord, Integer> CLUSTER_ID = createField(DSL.name("cluster_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>associations.player_id</code>.
     */
    public final TableField<AssociationsRecord, Integer> PLAYER_ID = createField(DSL.name("player_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>associations.association</code>.
     */
    public final TableField<AssociationsRecord, Double> ASSOCIATION = createField(DSL.name("association"), org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>associations.created_at</code>.
     */
    public final TableField<AssociationsRecord, Long> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>associations</code> table reference
     */
    public Associations() {
        this(DSL.name("associations"), null);
    }

    /**
     * Create an aliased <code>associations</code> table reference
     */
    public Associations(String alias) {
        this(DSL.name(alias), ASSOCIATIONS);
    }

    /**
     * Create an aliased <code>associations</code> table reference
     */
    public Associations(Name alias) {
        this(alias, ASSOCIATIONS);
    }

    private Associations(Name alias, Table<AssociationsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Associations(Name alias, Table<AssociationsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Associations(Table<O> child, ForeignKey<O, AssociationsRecord> key) {
        super(child, key, ASSOCIATIONS);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ASSOCIATIONS_CLUSTER_ID, Indexes.ASSOCIATIONS_PLAYER_AND_CLUSTER, Indexes.ASSOCIATIONS_PLAYER_ID);
    }

    @Override
    public List<ForeignKey<AssociationsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AssociationsRecord, ?>>asList(Keys.ASSOCIATIONS__ASSOCIATIONS_CLUSTER_ID_FKEY1, Keys.ASSOCIATIONS__ASSOCIATIONS_PLAYER_ID_FKEY1);
    }

    public Dbscan dbscan() {
        return new Dbscan(this, Keys.ASSOCIATIONS__ASSOCIATIONS_CLUSTER_ID_FKEY1);
    }

    public Players players() {
        return new Players(this, Keys.ASSOCIATIONS__ASSOCIATIONS_PLAYER_ID_FKEY1);
    }

    @Override
    public Associations as(String alias) {
        return new Associations(DSL.name(alias), this);
    }

    @Override
    public Associations as(Name alias) {
        return new Associations(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Associations rename(String name) {
        return new Associations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Associations rename(Name name) {
        return new Associations(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Double, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
