/*
 * This file is generated by jOOQ.
 */
package com.matt.nocom.server.postgres.codegen.tables;


import com.matt.nocom.server.postgres.codegen.DefaultSchema;
import com.matt.nocom.server.postgres.codegen.Indexes;
import com.matt.nocom.server.postgres.codegen.Keys;
import com.matt.nocom.server.postgres.codegen.tables.records.OldDbscanRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OldDbscan extends TableImpl<OldDbscanRecord> {

    private static final long serialVersionUID = 1490160846;

    /**
     * The reference instance of <code>old_dbscan</code>
     */
    public static final OldDbscan OLD_DBSCAN = new OldDbscan();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OldDbscanRecord> getRecordType() {
        return OldDbscanRecord.class;
    }

    /**
     * The column <code>old_dbscan.id</code>.
     */
    public final TableField<OldDbscanRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('dbscan_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>old_dbscan.cnt</code>.
     */
    public final TableField<OldDbscanRecord, Integer> CNT = createField(DSL.name("cnt"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>old_dbscan.x</code>.
     */
    public final TableField<OldDbscanRecord, Integer> X = createField(DSL.name("x"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>old_dbscan.z</code>.
     */
    public final TableField<OldDbscanRecord, Integer> Z = createField(DSL.name("z"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>old_dbscan.dimension</code>.
     */
    public final TableField<OldDbscanRecord, Short> DIMENSION = createField(DSL.name("dimension"), org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>old_dbscan.server_id</code>.
     */
    public final TableField<OldDbscanRecord, Short> SERVER_ID = createField(DSL.name("server_id"), org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>old_dbscan.is_core</code>.
     */
    public final TableField<OldDbscanRecord, Boolean> IS_CORE = createField(DSL.name("is_core"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>old_dbscan.cluster_parent</code>.
     */
    public final TableField<OldDbscanRecord, Integer> CLUSTER_PARENT = createField(DSL.name("cluster_parent"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>old_dbscan.disjoint_rank</code>.
     */
    public final TableField<OldDbscanRecord, Integer> DISJOINT_RANK = createField(DSL.name("disjoint_rank"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>old_dbscan.disjoint_size</code>.
     */
    public final TableField<OldDbscanRecord, Integer> DISJOINT_SIZE = createField(DSL.name("disjoint_size"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>old_dbscan.updated_at_approx</code>.
     */
    public final TableField<OldDbscanRecord, Long> UPDATED_AT_APPROX = createField(DSL.name("updated_at_approx"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>old_dbscan</code> table reference
     */
    public OldDbscan() {
        this(DSL.name("old_dbscan"), null);
    }

    /**
     * Create an aliased <code>old_dbscan</code> table reference
     */
    public OldDbscan(String alias) {
        this(DSL.name(alias), OLD_DBSCAN);
    }

    /**
     * Create an aliased <code>old_dbscan</code> table reference
     */
    public OldDbscan(Name alias) {
        this(alias, OLD_DBSCAN);
    }

    private OldDbscan(Name alias, Table<OldDbscanRecord> aliased) {
        this(alias, aliased, null);
    }

    private OldDbscan(Name alias, Table<OldDbscanRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> OldDbscan(Table<O> child, ForeignKey<O, OldDbscanRecord> key) {
        super(child, key, OLD_DBSCAN);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.OLD_DBSCAN_CLUSTER_ROOTS, Indexes.OLD_DBSCAN_DISJOINT_TRAVERSAL, Indexes.OLD_DBSCAN_INGEST, Indexes.OLD_DBSCAN_PKEY);
    }

    @Override
    public Identity<OldDbscanRecord, Integer> getIdentity() {
        return Keys.IDENTITY_OLD_DBSCAN;
    }

    @Override
    public UniqueKey<OldDbscanRecord> getPrimaryKey() {
        return Keys.OLD_DBSCAN_PKEY;
    }

    @Override
    public List<UniqueKey<OldDbscanRecord>> getKeys() {
        return Arrays.<UniqueKey<OldDbscanRecord>>asList(Keys.OLD_DBSCAN_PKEY);
    }

    @Override
    public List<ForeignKey<OldDbscanRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OldDbscanRecord, ?>>asList(Keys.OLD_DBSCAN__DBSCAN_DIMENSION_FKEY, Keys.OLD_DBSCAN__DBSCAN_SERVER_ID_FKEY, Keys.OLD_DBSCAN__DBSCAN_CLUSTER_PARENT_FKEY);
    }

    public Dimensions dimensions() {
        return new Dimensions(this, Keys.OLD_DBSCAN__DBSCAN_DIMENSION_FKEY);
    }

    public Servers servers() {
        return new Servers(this, Keys.OLD_DBSCAN__DBSCAN_SERVER_ID_FKEY);
    }

    public com.matt.nocom.server.postgres.codegen.tables.OldDbscan oldDbscan() {
        return new com.matt.nocom.server.postgres.codegen.tables.OldDbscan(this, Keys.OLD_DBSCAN__DBSCAN_CLUSTER_PARENT_FKEY);
    }

    @Override
    public OldDbscan as(String alias) {
        return new OldDbscan(DSL.name(alias), this);
    }

    @Override
    public OldDbscan as(Name alias) {
        return new OldDbscan(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OldDbscan rename(String name) {
        return new OldDbscan(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OldDbscan rename(Name name) {
        return new OldDbscan(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, Integer, Integer, Integer, Short, Short, Boolean, Integer, Integer, Integer, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
