/*
 * This file is generated by jOOQ.
 */
package com.matt.nocom.server.postgres.codegen.tables;


import com.matt.nocom.server.postgres.codegen.DefaultSchema;
import com.matt.nocom.server.postgres.codegen.Keys;
import com.matt.nocom.server.postgres.codegen.tables.records.SpatialRefSysRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpatialRefSys extends TableImpl<SpatialRefSysRecord> {

    private static final long serialVersionUID = -454410629;

    /**
     * The reference instance of <code>spatial_ref_sys</code>
     */
    public static final SpatialRefSys SPATIAL_REF_SYS = new SpatialRefSys();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpatialRefSysRecord> getRecordType() {
        return SpatialRefSysRecord.class;
    }

    /**
     * The column <code>spatial_ref_sys.srid</code>.
     */
    public final TableField<SpatialRefSysRecord, Integer> SRID = createField(DSL.name("srid"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>spatial_ref_sys.auth_name</code>.
     */
    public final TableField<SpatialRefSysRecord, String> AUTH_NAME = createField(DSL.name("auth_name"), org.jooq.impl.SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>spatial_ref_sys.auth_srid</code>.
     */
    public final TableField<SpatialRefSysRecord, Integer> AUTH_SRID = createField(DSL.name("auth_srid"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>spatial_ref_sys.srtext</code>.
     */
    public final TableField<SpatialRefSysRecord, String> SRTEXT = createField(DSL.name("srtext"), org.jooq.impl.SQLDataType.VARCHAR(2048), this, "");

    /**
     * The column <code>spatial_ref_sys.proj4text</code>.
     */
    public final TableField<SpatialRefSysRecord, String> PROJ4TEXT = createField(DSL.name("proj4text"), org.jooq.impl.SQLDataType.VARCHAR(2048), this, "");

    /**
     * Create a <code>spatial_ref_sys</code> table reference
     */
    public SpatialRefSys() {
        this(DSL.name("spatial_ref_sys"), null);
    }

    /**
     * Create an aliased <code>spatial_ref_sys</code> table reference
     */
    public SpatialRefSys(String alias) {
        this(DSL.name(alias), SPATIAL_REF_SYS);
    }

    /**
     * Create an aliased <code>spatial_ref_sys</code> table reference
     */
    public SpatialRefSys(Name alias) {
        this(alias, SPATIAL_REF_SYS);
    }

    private SpatialRefSys(Name alias, Table<SpatialRefSysRecord> aliased) {
        this(alias, aliased, null);
    }

    private SpatialRefSys(Name alias, Table<SpatialRefSysRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> SpatialRefSys(Table<O> child, ForeignKey<O, SpatialRefSysRecord> key) {
        super(child, key, SPATIAL_REF_SYS);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<SpatialRefSysRecord> getPrimaryKey() {
        return Keys.SPATIAL_REF_SYS_PKEY;
    }

    @Override
    public List<UniqueKey<SpatialRefSysRecord>> getKeys() {
        return Arrays.<UniqueKey<SpatialRefSysRecord>>asList(Keys.SPATIAL_REF_SYS_PKEY);
    }

    @Override
    public List<Check<SpatialRefSysRecord>> getChecks() {
        return Arrays.<Check<SpatialRefSysRecord>>asList(
              Internal.createCheck(this, DSL.name("spatial_ref_sys_srid_check"), "(((srid > 0) AND (srid <= 998999)))", true)
        );
    }

    @Override
    public SpatialRefSys as(String alias) {
        return new SpatialRefSys(DSL.name(alias), this);
    }

    @Override
    public SpatialRefSys as(Name alias) {
        return new SpatialRefSys(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpatialRefSys rename(String name) {
        return new SpatialRefSys(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpatialRefSys rename(Name name) {
        return new SpatialRefSys(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Integer, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
