/*
 * This file is generated by jOOQ.
 */
package com.matt.nocom.server.postgres.codegen.enums;


import com.matt.nocom.server.postgres.codegen.DefaultSchema;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum StatusesEnum implements EnumType {

    OFFLINE("OFFLINE"),

    QUEUE("QUEUE"),

    ONLINE("ONLINE");

    private final String literal;

    private StatusesEnum(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema() == null ? null : getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public String getName() {
        return "statuses_enum";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
