#!/bin/bash

set -e
set -u

function usage() {
    echo -n \
"Usage: $(basename "$0")
Publish container images.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker \
            login -u "${GITLAB_USER}" -p "${GITLAB_PASSWORD}" registry.gitlab.com;

        docker \
            push "registry.gitlab.com/fr1kin/nocom-http:latest";
    fi
fi
