/*
 * This file is generated by jOOQ.
 */
package com.matt.nocom.server.postgres.codegen.tables.records;


import com.matt.nocom.server.postgres.codegen.tables.Associations;
import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssociationsRecord extends TableRecordImpl<AssociationsRecord> implements Record4<Integer, Integer, Double, Long> {

    private static final long serialVersionUID = -979839730;

    /**
     * Setter for <code>associations.cluster_id</code>.
     */
    public void setClusterId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>associations.cluster_id</code>.
     */
    public Integer getClusterId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>associations.player_id</code>.
     */
    public void setPlayerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>associations.player_id</code>.
     */
    public Integer getPlayerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>associations.association</code>.
     */
    public void setAssociation(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>associations.association</code>.
     */
    public Double getAssociation() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>associations.created_at</code>.
     */
    public void setCreatedAt(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>associations.created_at</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Double, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Double, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Associations.ASSOCIATIONS.CLUSTER_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Associations.ASSOCIATIONS.PLAYER_ID;
    }

    @Override
    public Field<Double> field3() {
        return Associations.ASSOCIATIONS.ASSOCIATION;
    }

    @Override
    public Field<Long> field4() {
        return Associations.ASSOCIATIONS.CREATED_AT;
    }

    @Override
    public Integer component1() {
        return getClusterId();
    }

    @Override
    public Integer component2() {
        return getPlayerId();
    }

    @Override
    public Double component3() {
        return getAssociation();
    }

    @Override
    public Long component4() {
        return getCreatedAt();
    }

    @Override
    public Integer value1() {
        return getClusterId();
    }

    @Override
    public Integer value2() {
        return getPlayerId();
    }

    @Override
    public Double value3() {
        return getAssociation();
    }

    @Override
    public Long value4() {
        return getCreatedAt();
    }

    @Override
    public AssociationsRecord value1(Integer value) {
        setClusterId(value);
        return this;
    }

    @Override
    public AssociationsRecord value2(Integer value) {
        setPlayerId(value);
        return this;
    }

    @Override
    public AssociationsRecord value3(Double value) {
        setAssociation(value);
        return this;
    }

    @Override
    public AssociationsRecord value4(Long value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AssociationsRecord values(Integer value1, Integer value2, Double value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssociationsRecord
     */
    public AssociationsRecord() {
        super(Associations.ASSOCIATIONS);
    }

    /**
     * Create a detached, initialised AssociationsRecord
     */
    public AssociationsRecord(Integer clusterId, Integer playerId, Double association, Long createdAt) {
        super(Associations.ASSOCIATIONS);

        set(0, clusterId);
        set(1, playerId);
        set(2, association);
        set(3, createdAt);
    }
}
