/*
 * This file is generated by jOOQ.
 */
package com.matt.nocom.server.postgres.codegen.tables.records;


import com.matt.nocom.server.postgres.codegen.tables.HeatmapNether;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HeatmapNetherRecord extends TableRecordImpl<HeatmapNetherRecord> implements Record3<Integer, Integer, Long> {

    private static final long serialVersionUID = -1930068877;

    /**
     * Setter for <code>heatmap_nether.x</code>.
     */
    public void setX(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>heatmap_nether.x</code>.
     */
    public Integer getX() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>heatmap_nether.z</code>.
     */
    public void setZ(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>heatmap_nether.z</code>.
     */
    public Integer getZ() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>heatmap_nether.cnt</code>.
     */
    public void setCnt(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>heatmap_nether.cnt</code>.
     */
    public Long getCnt() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return HeatmapNether.HEATMAP_NETHER.X;
    }

    @Override
    public Field<Integer> field2() {
        return HeatmapNether.HEATMAP_NETHER.Z;
    }

    @Override
    public Field<Long> field3() {
        return HeatmapNether.HEATMAP_NETHER.CNT;
    }

    @Override
    public Integer component1() {
        return getX();
    }

    @Override
    public Integer component2() {
        return getZ();
    }

    @Override
    public Long component3() {
        return getCnt();
    }

    @Override
    public Integer value1() {
        return getX();
    }

    @Override
    public Integer value2() {
        return getZ();
    }

    @Override
    public Long value3() {
        return getCnt();
    }

    @Override
    public HeatmapNetherRecord value1(Integer value) {
        setX(value);
        return this;
    }

    @Override
    public HeatmapNetherRecord value2(Integer value) {
        setZ(value);
        return this;
    }

    @Override
    public HeatmapNetherRecord value3(Long value) {
        setCnt(value);
        return this;
    }

    @Override
    public HeatmapNetherRecord values(Integer value1, Integer value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HeatmapNetherRecord
     */
    public HeatmapNetherRecord() {
        super(HeatmapNether.HEATMAP_NETHER);
    }

    /**
     * Create a detached, initialised HeatmapNetherRecord
     */
    public HeatmapNetherRecord(Integer x, Integer z, Long cnt) {
        super(HeatmapNether.HEATMAP_NETHER);

        set(0, x);
        set(1, z);
        set(2, cnt);
    }
}
