/*
 * This file is generated by jOOQ.
 */
package com.matt.nocom.server.postgres.codegen.tables.records;


import com.matt.nocom.server.postgres.codegen.tables.OldDbscanProgress;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OldDbscanProgressRecord extends TableRecordImpl<OldDbscanProgressRecord> implements Record1<Long> {

    private static final long serialVersionUID = -1776305330;

    /**
     * Setter for <code>old_dbscan_progress.last_processed_hit_id</code>.
     */
    public void setLastProcessedHitId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>old_dbscan_progress.last_processed_hit_id</code>.
     */
    public Long getLastProcessedHitId() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<Long> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return OldDbscanProgress.OLD_DBSCAN_PROGRESS.LAST_PROCESSED_HIT_ID;
    }

    @Override
    public Long component1() {
        return getLastProcessedHitId();
    }

    @Override
    public Long value1() {
        return getLastProcessedHitId();
    }

    @Override
    public OldDbscanProgressRecord value1(Long value) {
        setLastProcessedHitId(value);
        return this;
    }

    @Override
    public OldDbscanProgressRecord values(Long value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OldDbscanProgressRecord
     */
    public OldDbscanProgressRecord() {
        super(OldDbscanProgress.OLD_DBSCAN_PROGRESS);
    }

    /**
     * Create a detached, initialised OldDbscanProgressRecord
     */
    public OldDbscanProgressRecord(Long lastProcessedHitId) {
        super(OldDbscanProgress.OLD_DBSCAN_PROGRESS);

        set(0, lastProcessedHitId);
    }
}
