---
- hosts: nhackindustries-vm
  become: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - { role: nhack.ansible }
    - { role: nhack.docker }
    - { role: nhack.nocom }
